Update memory optimization for 2022
asanetargoss/equilinox_guides pull request #1
Opened 2022-09-19 01:13 UTC by Azzurite

Instead of all the shenanigans with bash/powershell files, it's very simple to use Steam's launch options to set which Java should be used. Also, (now?) Equilinox uses `org.ninjacave.jarsplice.JarSpliceLauncher`, which runs a secondary Java process after the initial one. Thus it is necessary to adjust the `MANIFEST.MF` within the Equilinox jar if you want to increase/change the amount of memory the game is allowed to use.

I removed all references to older Java versions. I used AdoptOpenJDK 17 to test the most recent Equilinox version and everything worked nicely.

2022-09-20 04:30 UTC, asanetargoss requested changes
Goodness, I wrote this guide a long time ago. No idea people still stumbled upon it.

As much as I like the speediness of the script method, I must admit that a Steam launch wrapper is a bit better. But it needs some changes before I can be happy with it.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +- Change Equilinox Steam properties to `"C:\your-path-to-java\bin\javaw.exe" -jar EquilinoxWindows.jar %command%`
`%command%` is Windows-specific command line behavior. For Unix-like systems, you have to use `$command`. Something like `/path/to/java -jar input.jar $command`

I had another issue trying to get this custom Equilinox launch running on Linux Mint. `javaw` didn't exist so I had to use `java`, and the game needed to know where a few extra dependencies were. This command works for me on Linux Mint:

```sh
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}"; 
"/path/to/java" -jar input.jar $command
```

Note that the jar file is named different depending on the OS. This should be mentioned elsewhere in the guide as well. Sadly, I don't have a Mac machine to test with, but it is likely along the lines of `/path/to/java -jar name_of_jar $command`

(So yea, I wrote this guide back when I used Windows and it didn't quite work on Linux, oops!)

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +The most recent Java version is a much newer version than the old one that Equilinox uses, but should cause no issues when running the game. In case it does, it's pretty simple to revert to that vers
I still recommend explicitly stating the major version of Java that Equilinox has been tested to work with and the version that it historically used, and maybe a note that later versions may also work. This will help others with troubleshooting.

I do like Adoptium, though.

Regarding "revert": maybe say instead "use a different version", as "revert" implies the other version of Java needs to be uninstalled.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +To do that, navigate to Equilinox install directory. Open the file `EquilinoxWindows.jar` with 7zip. Navigate to the `META-INF` folder inside the zip. Select `MANIFEST.MF` and right-click -> Edit. Wh
While it's unlikely Equilinox will ever be updated again, it would probably be nice to add a note that an update will probably break this.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +This is a slightly advanced step and shouldn't normally be necessary. By default, the newer Java versions use 25% of your computers memory. As long as you have 4GB or more RAM, you should have more t
> your computer's memory

Also, again, it's best to be explicit about the version of Java used because the behavior of Java may change between versions.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +You will need to know the full file path for the version of Java you just installed.
I recommend moving this note into the top of the installation instructions. People may run the installer and not think to remember the path.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
>  - Run your command line, making it use your dedicated GPU if possible
So, with this overhauled guide, this instruction is now out-of-date and will need to be changed (Also, Steam achievements should work now I think?).

However, there's a bigger problem, this version of the guide no longer includes a fix where Equilinox won't run with the dedicated GPU on a hybrid graphics system (which is common for laptops).

In principle, running Steam itself with the dedicated GPU will cause all programs launched from it to also use your dedicated GPU. So, please also restore the "Run the game" section, but instead of opening the command line, opening Steam instead. Maybe add your own two cents, because I didn't realize at the time that not all gaming machines have hybrid graphics (some just use the Nvidia/AMD GPU for everything). But for hybrid graphics machines, having games run with integrated graphics really hurts performance, so it's important.

It turns out that there's a similar method to use the correct GPU on Linux, which I've written up in [a Minecraft modpack install guide](https://github.com/asanetargoss/HardcoreAlchemy/wiki/Getting-started/667b04213ba596d6759d5ff7739e1d297aacf6f7#using-multimc-for-the-first-time), but you don't have to add that.

2022-09-20 04:30 UTC, asanetargoss commented on performance/memory.md
> +Right-click Equilinox in the list of games in your Steam library, and select "Properties". A new window will open which should have a text field with the label "Launch options" in the middle. In this
Update this as well to include alternate OS instructions.

2022-09-20 20:37 UTC, Azzurite commented
I don't really care enough to address all these issues, sorry :) you can close this PR if you like

2022-09-21 03:30 UTC, asanetargoss commented
Hey, if you submit a pull request, expect to receive constructive criticism. That's just how it works.

Let me know if you change your mind.

2022-09-21 03:30 UTC, closed without merging

2022-09-21 13:12 UTC, Azzurite commented
> if you submit a pull request, expect to receive constructive criticism

I did expect that. I'm just telling you that I don't want to address all these things, since it would take a lot more time than I'm willing to allocate to this.

I think the changes I suggested here would have improved the guide, even though it's of course not perfect. Since you are the repository owner, it's your decision if you want to reject an improvement because it's not perfect.